/** Income Tax Act / Income-tax Rules Appendix I — WDV rates (India). */
export type IndiaDepreciationRate = {
  country: string;
  law: string;
  assetBlock: string;
  displayName: string;
  ratePercent: number;
  method: 'WDV';
  description: string;
};

export const indiaIncomeTaxDepreciationRates: IndiaDepreciationRate[] = [
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'BUILDING_RESIDENTIAL',
    displayName: 'Building - Residential',
    ratePercent: 5,
    method: 'WDV',
    description: 'Buildings mainly used for residential purposes, except hotels and boarding houses',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'BUILDING_NON_RESIDENTIAL',
    displayName: 'Building - Non Residential / Commercial',
    ratePercent: 10,
    method: 'WDV',
    description: 'Buildings other than mainly residential buildings',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'BUILDING_WATER_PROJECT',
    displayName: 'Building - Water Supply / Water Treatment Infrastructure',
    ratePercent: 40,
    method: 'WDV',
    description: 'Buildings for installing machinery and plant forming part of water supply or water treatment system under eligible infrastructure business',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'BUILDING_TEMPORARY',
    displayName: 'Purely Temporary Erections',
    ratePercent: 40,
    method: 'WDV',
    description: 'Purely temporary erections such as wooden structures',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'FURNITURE_AND_FITTINGS',
    displayName: 'Furniture and Fittings',
    ratePercent: 10,
    method: 'WDV',
    description: 'Furniture and fittings including electrical fittings',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'PLANT_AND_MACHINERY_GENERAL',
    displayName: 'Plant and Machinery - General',
    ratePercent: 15,
    method: 'WDV',
    description: 'Machinery and plant other than special rate assets',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'MOTOR_CAR_GENERAL',
    displayName: 'Motor Car - General',
    ratePercent: 15,
    method: 'WDV',
    description: 'Motor cars other than those used in business of running them on hire',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'MOTOR_CAR_SPECIAL_2019',
    displayName: 'Motor Car - Special 2019 Acquisition Window',
    ratePercent: 30,
    method: 'WDV',
    description: 'Motor cars acquired on or after 23-Aug-2019 but before 01-Apr-2020 and put to use before 01-Apr-2020',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'AEROPLANES_AEROENGINES',
    displayName: 'Aeroplanes - Aeroengines',
    ratePercent: 40,
    method: 'WDV',
    description: 'Aeroplanes and aeroengines',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'MOTOR_BUSES_LORRIES_TAXIS_ON_HIRE',
    displayName: 'Motor Buses / Lorries / Taxis used on Hire',
    ratePercent: 30,
    method: 'WDV',
    description: 'Motor buses, motor lorries and motor taxis used in business of running them on hire',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'MOTOR_BUSES_LORRIES_TAXIS_ON_HIRE_SPECIAL_2019',
    displayName: 'Motor Buses / Lorries / Taxis on Hire - Special 2019 Window',
    ratePercent: 45,
    method: 'WDV',
    description: 'Eligible vehicles acquired on or after 23-Aug-2019 but before 01-Apr-2020 and put to use before 01-Apr-2020',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'COMMERCIAL_VEHICLE_SPECIAL_2009',
    displayName: 'New Commercial Vehicle - Special 2009 Window',
    ratePercent: 40,
    method: 'WDV',
    description: 'New commercial vehicle acquired on or after 01-Jan-2009 but before 01-Oct-2009 and put to use before 01-Oct-2009',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'MOULDS_RUBBER_PLASTIC',
    displayName: 'Moulds used in Rubber and Plastic Goods Factories',
    ratePercent: 30,
    method: 'WDV',
    description: 'Moulds used in rubber and plastic goods factories',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'POLLUTION_CONTROL_EQUIPMENT',
    displayName: 'Air / Water / Solid Waste Pollution Control Equipment',
    ratePercent: 40,
    method: 'WDV',
    description: 'Specified air pollution, water pollution, and solid waste control equipment',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'SEMICONDUCTOR_MACHINERY',
    displayName: 'Semi-conductor Industry Machinery and Plant',
    ratePercent: 30,
    method: 'WDV',
    description: 'Machinery and plant used in semi-conductor industry as specified',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'LIFE_SAVING_MEDICAL_EQUIPMENT',
    displayName: 'Life Saving Medical Equipment',
    ratePercent: 40,
    method: 'WDV',
    description: 'Specified life saving medical equipment',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'CONTAINERS_GLASS_PLASTIC_REFILLS',
    displayName: 'Glass / Plastic Containers used as Refills',
    ratePercent: 40,
    method: 'WDV',
    description: 'Containers made of glass or plastic used as refills',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'COMPUTERS_SOFTWARE',
    displayName: 'Computers including Computer Software',
    ratePercent: 40,
    method: 'WDV',
    description: 'Computers including computer software',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'WATER_SUPPLY_TREATMENT_PLANT',
    displayName: 'Water Supply / Water Treatment Plant and Machinery',
    ratePercent: 40,
    method: 'WDV',
    description: 'Machinery and plant acquired and installed in eligible water supply or water treatment projects',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'SPECIAL_40_PERCENT_PLANT_MACHINERY',
    displayName: 'Special Plant and Machinery - 40%',
    ratePercent: 40,
    method: 'WDV',
    description: 'Specified special assets such as renewable energy devices, energy saving devices, books, gas cylinders, selected mining/salt/flour/sugar/steel industry items, and other listed 40% plant and machinery items',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'SHIPS',
    displayName: 'Ships',
    ratePercent: 20,
    method: 'WDV',
    description: 'Ocean-going ships, inland water vessels, and speed boats as specified',
  },
  {
    country: 'IN',
    law: 'Income Tax Act / Income-tax Rules Appendix I',
    assetBlock: 'INTANGIBLE_ASSETS',
    displayName: 'Intangible Assets',
    ratePercent: 25,
    method: 'WDV',
    description: 'Know-how, patents, copyrights, trademarks, licences, franchises, or similar business/commercial rights',
  },
];

export const indiaDepreciationSpecialGroups = [
  { group: 'Air Pollution Control Equipment', ratePercent: 40 },
  { group: 'Water Pollution Control Equipment', ratePercent: 40 },
  { group: 'Solid Waste Control / Recycling Equipment', ratePercent: 40 },
  { group: 'Life Saving Medical Equipment', ratePercent: 40 },
  { group: 'Renewable Energy Devices', ratePercent: 40 },
  { group: 'Energy Saving Devices', ratePercent: 40 },
  { group: 'Books - Professional / Lending Library', ratePercent: 40 },
  { group: 'Semi-conductor Industry Machinery', ratePercent: 30 },
  { group: 'Moulds used in Rubber and Plastic Goods Factories', ratePercent: 30 },
  { group: 'Motor Buses / Lorries / Taxis used on Hire', ratePercent: 30 },
  { group: 'Special 2019 Motor Vehicles', ratePercent: 30 },
  { group: 'Special 2019 Hire Vehicles', ratePercent: 45 },
];
